# Generated by Django 2.1 on 2019-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='course_id',
        ),
        migrations.AddField(
            model_name='chapters',
            name='teacher_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='teacher_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
